name: jahmm
favicon: null
layout_spectrum: 0.6131960093043745
typography_spectrum: 0.8912218457553536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.961256243288517
purpose: []
